[package]
name = "scomm-openpgp-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "C ABI for scomm-openpgp (Dart / Flutter FFI)."

[lib]
name = "scomm_openpgp"
crate-type = ["cdylib", "staticlib"]

[features]
default = ["rustcrypto"]
rustcrypto = ["scomm-openpgp-sequoia/rustcrypto"]
openssl = ["scomm-openpgp-sequoia/openssl"]

[dependencies]
scomm-openpgp-core.workspace = true
scomm-openpgp-sequoia = { path = "../scomm-openpgp-sequoia", default-features = false }
serde_json = "1"
openssl.workspace = true
